[package]
name = "plotters-bug"
version = "0.1.0"
edition = "2021"

[dependencies]
plotters = { git = "https://github.com/plotters-rs/plotters.git", rev = "af0b63ca2c0ca18780ec9e92730fa97a444dbfca", features = [
    "area_series",
] }
